version: "3"

networks:
  mongonet:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: test
#      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    networks:
      - "mongonet"

  mongo-seed:
    build:
      context: ./packages/database
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - "mongonet"
